### ISSUE TITLE
boss-mdns/build fails

### ISSUE THREAD

**Issue by maxlath** [tableflip/boss#32]
running `npm install -g process-boss`, I get the following error

```
> boss-mdns@2.2.4 install /home/myuserdir/.nvm/v0.10.35/lib/node_modules/process-boss/node_modules/boss-mdns
> node-gyp rebuild

make: entering the directory « /home/myuserdir/.nvm/v0.10.35/lib/node_modules/process-boss/node_modules/boss-mdns/build »
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h : No such a file or directory
compilation finished.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: leaving the directory « /home/myuserdir/.nvm/v0.10.35/lib/node_modules/process-boss/node_modules/boss-mdns/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/myuserdir/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.11.0-23-generic
gyp ERR! command "node" "/home/myuserdir/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
cwd /home/myuserdir/.nvm/v0.10.35/lib/node_modules/process-boss/node_modules/boss-mdns
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing boss-mdns@2.2.4
```
NB: I had to translate some lines of the above report from French, it might not be the exact terms

**Comment by achingbrain** [comment]
mdns is an optional dependency that essentially lets you connect boss-web to boss instances on the local network without knowing the host/port ahead of time.

If you want to use that functionality on Linux you need to install Avahi before installing boss with:

```sh
$ sudo apt-get install libavahi-compat-libdnssd-dev
```

If the functionality is not important to you, it's an optional dependency so you can ignore the compilation failure.

**Comment by maxlath** [comment]
indeed, no more fail after installing libavahi-compat-libdnssd-dev
